# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PharmacieDeleteBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, pharmacie_id: str=None):  # noqa: E501
        """PharmacieDeleteBody - a model defined in Swagger

        :param pharmacie_id: The pharmacie_id of this PharmacieDeleteBody.  # noqa: E501
        :type pharmacie_id: str
        """
        self.swagger_types = {
            'pharmacie_id': str
        }

        self.attribute_map = {
            'pharmacie_id': 'pharmacie_id'
        }
        self._pharmacie_id = pharmacie_id

    @classmethod
    def from_dict(cls, dikt) -> 'PharmacieDeleteBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The pharmacie_delete_body of this PharmacieDeleteBody.  # noqa: E501
        :rtype: PharmacieDeleteBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pharmacie_id(self) -> str:
        """Gets the pharmacie_id of this PharmacieDeleteBody.


        :return: The pharmacie_id of this PharmacieDeleteBody.
        :rtype: str
        """
        return self._pharmacie_id

    @pharmacie_id.setter
    def pharmacie_id(self, pharmacie_id: str):
        """Sets the pharmacie_id of this PharmacieDeleteBody.


        :param pharmacie_id: The pharmacie_id of this PharmacieDeleteBody.
        :type pharmacie_id: str
        """
        if pharmacie_id is None:
            raise ValueError("Invalid value for `pharmacie_id`, must not be `None`")  # noqa: E501

        self._pharmacie_id = pharmacie_id
