# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProductsDeleteBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, product_id: str=None):  # noqa: E501
        """ProductsDeleteBody - a model defined in Swagger

        :param product_id: The product_id of this ProductsDeleteBody.  # noqa: E501
        :type product_id: str
        """
        self.swagger_types = {
            'product_id': str
        }

        self.attribute_map = {
            'product_id': 'product_id'
        }
        self._product_id = product_id

    @classmethod
    def from_dict(cls, dikt) -> 'ProductsDeleteBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The products_delete_body of this ProductsDeleteBody.  # noqa: E501
        :rtype: ProductsDeleteBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def product_id(self) -> str:
        """Gets the product_id of this ProductsDeleteBody.


        :return: The product_id of this ProductsDeleteBody.
        :rtype: str
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id: str):
        """Sets the product_id of this ProductsDeleteBody.


        :param product_id: The product_id of this ProductsDeleteBody.
        :type product_id: str
        """
        if product_id is None:
            raise ValueError("Invalid value for `product_id`, must not be `None`")  # noqa: E501

        self._product_id = product_id
